openapi: 3.0.0
info:
  title: Substantia REST API
  version: 1.0.0
  description: REST API for Substantia - a subscription-based social media web application.

securityDefinitions:
  JwtAuth:
    type: apiKey
    in: header
    name: Authorization
    description: JWT token obtained during user login

paths:
  /api/register:
    post:
      summary: User registration
      parameters:
        - name: email
          in: body
          type: string
          required: true
        - name: username
          in: body
          type: string
          required: true
        - name: slug
          in: body
          type: string
          required: true
        - name: password
          in: body
          type: string
          required: true
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  username:
                    type: string
                  slug:
                    type: string
                  oAuth:
                    type: boolean
                  hasChannel:
                    type: boolean
                  subscriptionPrice:
                    type: number
                    nullable: true
                  avatar:
                    type: string
                    nullable: true
                  banner:
                    type: string
                    nullable: true
                  profileVideo:
                    type: string
                    nullable: true
                  facebook:
                    type: string
                    nullable: true
                  instagram:
                    type: string
                    nullable: true
                  twitter:
                    type: string
                    nullable: true
                  description:
                    type: string
                    nullable: true
                  createdAt:
                    type: string
        422:
          description: Validation error, duplicate e-mail or duplicate slug
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"


definitions:
  Error:
    type: object
    properties:
      message:
        type: string