openapi: 3.0.0
info:
  title: Substantia REST API
  version: 1.0.0
  description: REST API for Substantia - a subscription-based social media web application.

securityDefinitions:
  JwtAuth:
    type: apiKey
    in: header
    name: Authorization
    description: JWT token obtained during user login
